services:
  minio:
    image: minio/minio:latest
    env_file: "dev.env"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  minio-data: